### ISSUE TITLE
Reference Scaling: Dependent on setting units

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#17]
In the Module Reference Scaling, the conversion is only applied if the 'Units' field has a value. This field should be optional because some measurement types may be unitless. However, this bug is not necessarily high priority, because the workaround is easy (just filling the field it with any text).

**Comment by franciscoaleixo** [comment]
How do we identify in these cases those values when we export to CSV? At the moment we're identifying the following way: "line_name (px)" and "line_name(unit_name)"

**Comment by ruiprieto** [comment]
Good point. We should leave it as it is. As long as the field is not empty, it works fine. I suggest closing this issue as solved.

**Comment by ruiprieto** [comment]
This issue is no longer an issue. I wave my white tissue to this issue, while saying 'will not miss you'
