### ISSUE TITLE
Reference Scaling: rouding of length in pixels

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#18]
In the module Reference Scaling, when a line value is imported, it rounds the pixel value to the nearest integer (for example 46.31->46; 54.74->55). The rounded value is the value used in the calculation and then applied to all measured segments, lowering the precision of the measurements. We should have a precision of two decimal places. 

As an effect of this process, the length of the segment that was used as a scale is back-calculated, resulting in a different value than the true value.

**Comment by franciscoaleixo** [comment]
Fixed. Will be available in the next version 👍
