### ISSUE TITLE
Reference scaling: Reference

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#19]
Do not understand the usage of the 'Reference' tick box. Is this to enable drawing a reference scale in the future? In that case, I suggest changing the text to: "Draw scale on image"

**Comment by franciscoaleixo** [comment]
At the moment this is not implemented at all, i.e. the Reference checkbox does nothing for now. The idea was to reference the line's length. This means if we changed the line's length, then the scale would also update accordingly. At the moment this is not updated and probably not that useful so it might not even be implemented.

**Comment by ruiprieto** [comment]
Agreed; I do not envisage a scenario in which this functionality could be useful.

**Comment by franciscoaleixo** [comment]
Looks like it will be removed next version then 👍
