### ISSUE TITLE
D/f ratio

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#21]
The scaling formula based on a pin-hole camera model is 

〖Anat〗_cm= 〖Anat〗_px  * ((Sw*(H+β)*100))/(Fl*imW)

Where 
〖Anat〗_cm ~ measured structure in cm
〖Anat〗_px  ~ measured structure in pixel units
  Sw ~ sensor width in mm
  imW ~ sensor (image) size in pixel units
  Fl the focal length in mm
  H is the distance (height in the case of drones) of sensor to object
  ß is a correction factor for cases when the distance does not take the value of H (for example, a drone that is not lifting off at sea level)

in V 0.3 the field for ß is missing; that field should be able to accept any value (+/-) in metres, with two decimal places.

**Comment by franciscoaleixo** [comment]
Implemented in v0.3.1.
