### ISSUE TITLE
Lines - lines remain on screen after deletion

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#23]
![lines1](https://user-images.githubusercontent.com/32093541/38690024-a4cb8af2-3e6c-11e8-95c5-f1f3774db13c.jpg)
![lines2](https://user-images.githubusercontent.com/32093541/38690026-a4fa8f50-3e6c-11e8-9d6c-2a31df6d5a71.jpg)
![lines3](https://user-images.githubusercontent.com/32093541/38690029-a52a0b0e-3e6c-11e8-8c9d-9bae28e27c86.jpg)

NOTE: In the example images, Line 1 is the long, horizontal line

Displaying of lines is strange and unpredictable when deleting; several behaviours were recorded:

1 - Line disappears from image panel, as expected, when deleted;
2 - Line is still visible after deletion; this behaviour is corrected by choosing another image to be displayed and then coming back to the original image (ex. lines3.jpg);
3 - If more than one line is displayed, deletion of line 'x' results in line 'y' being hidden from display (ex  lines2.jpg); this behaviour is corrected by choosing another image to be displayed and then coming back to the original image (ex. lines3.jpg).

These behaviours seem to occur randomly.

**Comment by franciscoaleixo** [comment]
Fixed in version 0.3.1.
