### ISSUE TITLE
CSV export - Lists do not match

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#25]
![csv current](https://user-images.githubusercontent.com/32093541/38693100-725d2590-3e75-11e8-8d6c-cfea62bfea73.jpg)
![actual_list](https://user-images.githubusercontent.com/32093541/38693380-3b9491f0-3e76-11e8-817c-092df64180f2.jpg)

The name/address of the first (or one) image in the csv list does not correspond to the actual image. 
This behaviour does not appear to happen always; in some sessions the csv and the images in the software match.

**Comment by franciscoaleixo** [comment]
@ruiprieto Could you please test again on the next version (v0.3.1)? Didn't really reproduce it but it could still be there. Will close but reopen if you find it again.
