### ISSUE TITLE
CSV Table - table layout

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#26]
Currently, csv export separates records by using one line for record name, one line for headers, and one line for results
To streamline data analysis, all information (source and data) from a record should be displayed in a single line, with a unique (common) header line at the top. Ideally, selected metadata would also be exported with each record. In alternative all metadata should be exported.

![current_csv](https://user-images.githubusercontent.com/32093541/38730687-0cf72948-3f07-11e8-8b6e-9ce4ccccc468.jpg)

V

![goal_csv](https://user-images.githubusercontent.com/32093541/38730720-2c958bfa-3f07-11e8-9d3a-84dc352543e5.jpg)

**Comment by franciscoaleixo** [comment]
Implemented in 0.3.1:
 - Metadata fields to export can now be selected;
 - CSV Structure will follow the one described above;
 - Layers values with the same name will be on the same column.
