### ISSUE TITLE
V 0.3.1 Image memory management

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#27]
In V 3.0.1 only few (one or two) images can be loaded at a time.

**Comment by franciscoaleixo** [comment]
I don't actually see that, seems the same to me as when we talked about this. Probably JVM related (e.g. if it's 32 or 64 bit) and the RAM available.

This will be looked into but it's not related to 3.0.1 I think. Seems the same as before.

**Comment by ruiprieto** [comment]
Updating to Java V 1.8.0_171-b11 64 bits seems to have resolved the issue.
