### ISSUE TITLE
V 0.3.1 Delete image not working properly

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#28]
After deleting an image from project list, the image presented in the viewing panel is the deleted one (and not the remaining in the list); closing the program after saving with the same name caused loss of all stored work.
![bug_image mixed](https://user-images.githubusercontent.com/32093541/39368967-8e451752-4a2a-11e8-8b7a-fbb5af190b85.jpg)

**Comment by franciscoaleixo** [comment]
I think it's fixed for the next release (either 0.3.2 or 0.4), but please re-open if the issue persists after that.
