### ISSUE TITLE
V 0.3.1 Low precision in Scale by Reference

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#29]
When calculating a scale using a reference line, the precision of the calculation is not enough to present results with two decimal places.
In the example, the scale was set as 372.24 px = 50 cm, based on Line_1. Thus the result expected for the same line would be exactly 50 cm; however as seen in the image, the result that is returned is 49.88 cm.
The source of the error is probably related to low precision of the when calculating the relation. Apparently, when the division is made, the result is computed to only 3 significant decimal places. To avoid that problem, the precision of the calculation must be increased. To present the results with two significant decimal places the results of the relation (pixels/known scale) must be computed with a precision of at least 5 decimal places.

![scaling](https://user-images.githubusercontent.com/32093541/39371425-2e990f5a-4a31-11e8-83a2-031af66bb35e.jpg)

**Comment by franciscoaleixo** [comment]
Is it only the scale that needs this kind of precision? The scale now has 17 significant decimal places since it's not shown to the user, so we can have the maximum precision available.

This will be available next release.

**Comment by ruiprieto** [comment]
@franciscoaleixo wrote "Is it only the scale that needs this kind of precision? "

The precision should be as high as possible when performing any of the calculations to avoid rounding issues. Only when presenting the results we should restrict to a few decimal places.
