### ISSUE TITLE
V0.3.1 Zoom and image position not recovered upon re-opening session

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#30]
When re-opening a session saved earlier, the position and zoom level of the images when measurements were made are not recovered. As a result the position and size of the lines do not match those of the object being measured. See image below

![bug_save_position_zoom](https://user-images.githubusercontent.com/32093541/41031341-e93238a2-696f-11e8-9a76-395dd8c446ea.jpg)

**Comment by franciscoaleixo** [comment]
I agree this is high priority but I can't really reproduce it though. Does it happen all the time? Or only under certain circumstances?

**Comment by ruiprieto** [comment]
I  noticed the problem and then tried and succeeded to replicate in my machine. W7 Pro 64 bits; Intel i5-2450M CPU @ 2.5GHz; 8GB RAM; JAVA 1.8.0_161-b12. My machine is running slow so it might have something to do with memory management.

**Comment by franciscoaleixo** [comment]
If you can try it again it would be great. If it still doesn't work we can try to test with the next release version and see if it's still persists.

**Comment by ruiprieto** [comment]
Will do and post results

**Comment by ruiprieto** [comment]
Still happening on different machines... cannot yet see a pattern for the problem.

**Comment by franciscoaleixo** [comment]
From the images, it looks more like the layers are actually matching the wrong images no? The layers of the first image seem to belong to the second. I'll be working on this right now.

**Comment by franciscoaleixo** [comment]
Identified and fixed. Fix waiting to be merged. @ruiprieto please check this and reopen if it persists in the next version.
