### ISSUE TITLE
Camera Calibration not working in all systems

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#34]
Camera Calibration module window not opening in a test machine:

Intel i7-8550U, 1.8GHz 2.0 GHz
8 GB RAM
64-bit, W10 Pro
JAVA jre-8u201-windows-x64

**Comment by franciscoaleixo** [comment]
This is because OpenCV is probably missing in your test machine. You should have 'opencv_java342.dll' in the libs folder.

I will try to incorporate OpenCV somehow in the next versions.

**Comment by ruiprieto** [comment]
Great tip. Will add that to the manual.

**Comment by ruiprieto** [comment]
The information was added to the Wiki and manual
