### ISSUE TITLE
V5.0.1 Saving only saves images that had been selected for presentation in work panel

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#38]
After loading multiple images in the Navigation panel, if one tries to save the project only those images that had been selected to be presented in the Work panel will be saved in the axml file. Images that were loaded in the Navigation panel but not selected at least once, will not appear in the axml and consequently not loaded the next time the project is loaded.

**Comment by franciscoaleixo** [comment]
Fixed for the next version.
