### ISSUE TITLE
File sorting

### ISSUE THREAD

**Issue by ruiprieto** [franciscoaleixo/photogrammetry#9]
File list in the file import window should be sorted automatically (ascending), with priority for numerical and then for alphabetical order. Example below:

001.jpg
003_a.jpg
003_b.jpg
006.jpg
007.jpg
008.jpg
DSC1028.jpg
DSC1029.jpg

**Comment by franciscoaleixo** [comment]
I'm not sure this should be done automatically or if we should add an option to sort it.

What should happen in the following case?
Let's say we import 3 files: b.png, c.png, d.png. Lets assume they get added alphabetically, thats fine.

But after, what if we add the a.png file? Isn't it a bit weird that it jumps to the first position on the list and not the last as you would expect?

**Comment by ruiprieto** [comment]
Agree; an option to sort would be preferable

**Comment by franciscoaleixo** [comment]
I think this is fixed in 0.6.1 (sorts alphabetically)
